# Generated by Django 5.0.1 on 2024-02-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('pass1', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
    ]
