# Generated by Django 5.0.1 on 2024-02-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password1',
            field=models.CharField(max_length=100),
        ),
    ]
