# Generated by Django 5.0.1 on 2024-03-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_alter_signup_password1'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('firstname', models.TextField(max_length=100)),
                ('lastname', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
    ]
